# Generated by Django 5.1.2 on 2024-11-08 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convite',
            name='usuario_convindante',
        ),
        migrations.RemoveField(
            model_name='convite',
            name='usuario_convidado',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='convite',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('usado', 'Usado'), ('expirado', 'Expirado')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('convidados', models.ManyToManyField(blank=True, to='content_app.member')),
                ('convidante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('convites_enviados', models.ManyToManyField(blank=True, related_name='convites_enviados', to='content_app.convite')),
            ],
        ),
        migrations.AddField(
            model_name='cadastro',
            name='membro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content_app.member'),
        ),
        migrations.AddField(
            model_name='convite',
            name='membro_convidado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_recebidos', to='content_app.member'),
        ),
        migrations.AddField(
            model_name='convite',
            name='membro_convindante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='convites_feitos', to='content_app.member'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
