# Generated by Django 5.1.3 on 2024-11-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_rename_recompensas_member_convites_aceitos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='convites_aceitos',
        ),
    ]
