# Generated by Django 5.1.3 on 2024-11-21 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0006_rename_member_membro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membro',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='convite',
            old_name='destinatario',
            new_name='userDestinatario',
        ),
        migrations.RenameField(
            model_name='convite',
            old_name='remetente',
            new_name='userRemetente',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='membro',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tipo',
            field=models.CharField(choices=[('Comentários gerais', 'Comentários gerais'), ('Sugestões de melhoria', 'Sugestões de melhoria'), ('Problemas tecnicos', 'Problemas tecnicos')], default='Comentários gerais', max_length=50),
        ),
    ]
