# Generated by Django 5.1.3 on 2024-11-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0009_rename_membro_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Aceito', 'Aceito'), ('Expirado', 'Expirado')], default='Aguardando', max_length=50),
        ),
    ]
