# Generated by Django 5.1.3 on 2024-11-21 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0010_alter_convite_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convite',
            old_name='userDestinatario',
            new_name='destinatario',
        ),
    ]
