# Generated by Django 5.1.3 on 2024-11-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0011_rename_userdestinatario_convite_destinatario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convite',
            old_name='destinatario',
            new_name='userDestinatario',
        ),
    ]
